/**
 * Game title map — exe name to display title.
 * Exe names sourced from PCGamingWiki, Steam crash logs, and PresentMon output.
 * For any unrecognized process, the fallback strips .exe and title-cases the name.
 */
export const GAME_TITLE_MAP: Record<string, string> = {
  "7daystodie.exe": "7 Days to Die",
  "ac-win64-shipping.exe": "Assassin's Creed Shadows",
  "ac.exe": "Assassin's Creed",
  "acbf.exe": "Assassin's Creed IV: Black Flag",
  "acmirage.exe": "Assassin's Creed Mirage",
  "acodyssey.exe": "Assassin's Creed Odyssey",
  "acorigins.exe": "Assassin's Creed Origins",
  "acs.exe": "Assetto Corsa",
  "acshadows.exe": "Assassin's Creed Shadows",
  "acsyndicate.exe": "Assassin's Creed Syndicate",
  "acu.exe": "Assassin's Creed Unity",
  "acvalhalla.exe": "Assassin's Creed Valhalla",
  "ageofdecadence.exe": "The Age of Decadence",
  "alan_wake_2.exe": "Alan Wake 2",
  "alanwake2.exe": "Alan Wake 2",
  "alien_isolation.exe": "Alien: Isolation",
  "amnesia.exe": "Amnesia: The Dark Descent",
  "amnesiarebirth.exe": "Amnesia: Rebirth",
  "arma3.exe": "Arma 3",
  "arma3battleye.exe": "Arma 3",
  "arma4.exe": "Arma 4",
  "avengers.exe": "Marvel's Avengers",
  "baldursgate3.exe": "Baldur's Gate 3",
  "batmanarkhamasylum.exe": "Batman: Arkham Asylum",
  "batmanarkhamcity.exe": "Batman: Arkham City",
  "batmanarkhamknight.exe": "Batman: Arkham Knight",
  "batmanarkhamknightlauncher.exe": "Batman: Arkham Knight",
  "batmanarkhamorigins.exe": "Batman: Arkham Origins",
  "bf1.exe": "Battlefield 1",
  "bf2042.exe": "Battlefield 2042",
  "bf3.exe": "Battlefield 3",
  "bf4.exe": "Battlefield 4",
  "bf6.exe": "Battlefield 6",
  "bfdc.exe": "Battlefield: Dark Company",
  "bfv.exe": "Battlefield V",
  "bg3.exe": "Baldur's Gate 3",
  "bioshock.exe": "BioShock",
  "bioshock2.exe": "BioShock 2",
  "bioshock2hd.exe": "BioShock 2 Remastered",
  "bioshockhd.exe": "BioShock Remastered",
  "bioshockinfinite.exe": "BioShock Infinite",
  "bl3.exe": "Borderlands 3",
  "blackops4.exe": "Call of Duty: Black Ops 4",
  "blackops6.exe": "Call of Duty: Black Ops 6",
  "borderlands2.exe": "Borderlands 2",
  "borderlands3.exe": "Borderlands 3",
  "callofcthulhu.exe": "Call of Cthulhu",
  "chernobylite.exe": "Chernobylite",
  "chernobylitecomplete.exe": "Chernobylite",
  "cities.exe": "Cities: Skylines",
  "cities2.exe": "Cities: Skylines II",
  "citiesskylines2.exe": "Cities: Skylines II",
  "cod.exe": "Call of Duty",
  "concord.exe": "Concord",
  "control_dx11.exe": "Control",
  "control_dx12.exe": "Control",
  "crysis.exe": "Crysis Remastered",
  "crysis2.exe": "Crysis 2 Remastered",
  "crysis3.exe": "Crysis 3 Remastered",
  "crysiswars.exe": "Crysis Wars",
  "cyberpunk2077.exe": "Cyberpunk 2077",
  "darksouls.exe": "Dark Souls Remastered",
  "darksouls2.exe": "Dark Souls II",
  "darksouls3.exe": "Dark Souls III",
  "daysgone.exe": "Days Gone",
  "dayz.exe": "DayZ",
  "deadspace.exe": "Dead Space",
  "deadspace2.exe": "Dead Space 2",
  "deadspaceremake.exe": "Dead Space (Remake)",
  "deathloop.exe": "Deathloop",
  "deathoftheoutsider.exe": "Dishonored: Death of the Outsider",
  "deathstranding.exe": "Death Stranding",
  "deathstranding2.exe": "Death Stranding 2",
  "deusex.exe": "Deus Ex",
  "dirtrally2.exe": "DiRT Rally 2.0",
  "dishonored.exe": "Dishonored",
  "dishonored2.exe": "Dishonored 2",
  "divinity.exe": "Divinity: Original Sin 2",
  "divinityoriginalsin2.exe": "Divinity: Original Sin 2",
  "division.exe": "Tom Clancy's The Division",
  "division2.exe": "Tom Clancy's The Division 2",
  "doom_x64.exe": "DOOM (2016)",
  "doom.exe": "DOOM (2016)",
  "doometernall.exe": "DOOM Eternal",
  "doomx64vk.exe": "DOOM Eternal",
  "dragonage.exe": "Dragon Age: Origins",
  "dragonage2.exe": "Dragon Age II",
  "dragonageinquisition.exe": "Dragon Age: Inquisition",
  "dragonageveilguard.exe": "Dragon Age: The Veilguard",
  "dragonsdogma.exe": "Dragon's Dogma: Dark Arisen",
  "dragonsdogma2.exe": "Dragon's Dogma 2",
  "dysonsphereprog.exe": "Dyson Sphere Program",
  "eft.exe": "Escape from Tarkov",
  "eldenring.exe": "Elden Ring",
  "elex.exe": "ELEX",
  "elex2.exe": "ELEX II",
  "enshrouded.exe": "Enshrouded",
  "escapefromtarkov.exe": "Escape from Tarkov",
  "f12022.exe": "F1 2022",
  "f12023.exe": "F1 2023",
  "f12024.exe": "F1 2024",
  "f12025.exe": "F1 2025",
  "factorio.exe": "Factorio",
  "fallout3.exe": "Fallout 3",
  "fallout4.exe": "Fallout 4",
  "fallout4vr.exe": "Fallout 4 VR",
  "fallout76.exe": "Fallout 76",
  "falloutnv.exe": "Fallout: New Vegas",
  "farcry.exe": "Far Cry",
  "farcry3.exe": "Far Cry 3",
  "farcry3blooddragon.exe": "Far Cry 3: Blood Dragon",
  "farcry4.exe": "Far Cry 4",
  "farcry5.exe": "Far Cry 5",
  "farcry6.exe": "Far Cry 6",
  "farcryneward.exe": "Far Cry New Dawn",
  "farcryprimal.exe": "Far Cry Primal",
  "ff16.exe": "Final Fantasy XVI",
  "ff7.exe": "Final Fantasy VII Remake",
  "ff7rebirth.exe": "Final Fantasy VII Rebirth",
  "ff7remake_launcher.exe": "Final Fantasy VII Remake",
  "ffxv.exe": "Final Fantasy XV",
  "finalfantasyxv.exe": "Final Fantasy XV",
  "flightsimulator.exe": "Microsoft Flight Simulator",
  "forzamotorsport.exe": "Forza Motorsport",
  "ghostoftsushima.exe": "Ghost of Tsushima",
  "ghostreconbreakpoint.exe": "Ghost Recon Breakpoint",
  "ghostreconwildlands.exe": "Ghost Recon Wildlands",
  "ghostrunner.exe": "Ghostrunner",
  "ghostrunner2.exe": "Ghostrunner 2",
  "gloomwood.exe": "Gloomwood",
  "godofwar.exe": "God of War",
  "godofwarragnarok-win64-shipping.exe": "God of War: Ragnarök",
  "gothic.exe": "Gothic",
  "gothic2.exe": "Gothic 2",
  "greenh.exe": "Green Hell",
  "greenhell.exe": "Green Hell",
  "gta5.exe": "Grand Theft Auto V",
  "gta6.exe": "Grand Theft Auto VI",
  "halo1.exe": "Halo: Combat Evolved",
  "haloinfiniite.exe": "Halo Infinite",
  "haloinfinite.exe": "Halo Infinite",
  "halomcc-win64-shipping.exe": "Halo: The Master Chief Collection",
  "helldivers2.exe": "Helldivers 2",
  "hfw-win64-shipping.exe": "Horizon Forbidden West",
  "horizon4.exe": "Forza Horizon 4",
  "horizon5.exe": "Forza Horizon 5",
  "horizonforbiddenwest-win64-shipping.exe": "Horizon Forbidden West",
  "horizonforbiddenwest.exe": "Horizon Forbidden West",
  "horizonzerodawn.exe": "Horizon Zero Dawn Remastered",
  "horizonzerodawnremastered.exe": "Horizon Zero Dawn Remastered",
  "icarus-win64-shipping.exe": "Icarus",
  "icarus.exe": "Icarus",
  "jagexlauncher.exe": "Jagex Launcher",
  "runelite.exe": "RuneLite",
  "justcause3.exe": "Just Cause 3",
  "justcause4.exe": "Just Cause 4",
  "kcd2.exe": "Kingdom Come: Deliverance II",
  "kingdomcome.exe": "Kingdom Come: Deliverance",
  "kingdomcome2.exe": "Kingdom Come: Deliverance II",
  "lastofuspart1.exe": "The Last of Us Part I",
  "lastofuspart2.exe": "The Last of Us Part II Remastered",
  "liesofp.exe": "Lies of P",
  "mafia-win64-shipping.exe": "Mafia: The Old Country",
  "mafia.exe": "Mafia: Definitive Edition",
  "mafia2de.exe": "Mafia II: Definitive Edition",
  "mafia3.exe": "Mafia III",
  "mafia4.exe": "Mafia: The Old Country",
  "mafiaoldcountry.exe": "Mafia: The Old Country",
  "mafiaremastered.exe": "Mafia: Definitive Edition",
  "mankind_divided.exe": "Deus Ex: Mankind Divided",
  "masseffect1.exe": "Mass Effect 1 [Legendary Edition]",
  "masseffect2.exe": "Mass Effect 2 [Legendary Edition]",
  "masseffect3.exe": "Mass Effect 3 [Legendary Edition]",
  "masseffectandromeda.exe": "Mass Effect: Andromeda",
  "masseffectlegendaryedition.exe": "Mass Effect Legendary Edition",
  "me1game-win64-shipping.exe": "Mass Effect 1 [Legendary Edition]",
  "me2game-win64-shipping.exe": "Mass Effect 2 [Legendary Edition]",
  "me3game-win64-shipping.exe": "Mass Effect 3 [Legendary Edition]",
  "metro2033redux.exe": "Metro 2033 Redux",
  "metroexodus.exe": "Metro Exodus",
  "metroexodusenhanced.exe": "Metro Exodus Enhanced Edition",
  "metrolastlightredux.exe": "Metro: Last Light Redux",
  "mhrise.exe": "Monster Hunter Rise",
  "mhwilds.exe": "Monster Hunter Wilds",
  "microsoftflightsimulator.exe": "Microsoft Flight Simulator",
  "milemorales.exe": "Marvel's Spider-Man: Miles Morales",
  "modernwarfare.exe": "Call of Duty: Modern Warfare",
  "modernwarfare2.exe": "Call of Duty: Modern Warfare II",
  "modernwarfare3.exe": "Call of Duty: Modern Warfare III",
  "monsterh-win64-shipping.exe": "Monster Hunter: World",
  "monsterhunterworld.exe": "Monster Hunter: World",
  "msfs.exe": "Microsoft Flight Simulator",
  "needforseedunbound.exe": "Need for Speed: Unbound",
  "needforspeedheat.exe": "Need for Speed: Heat",
  "newcolossus.exe": "Wolfenstein II: The New Colossus",
  "neworder.exe": "Wolfenstein: The New Order",
  "nfsheat.exe": "Need for Speed: Heat",
  "nfsunbound.exe": "Need for Speed: Unbound",
  "nioh2.exe": "Nioh 2",
  "nms.exe": "No Man's Sky",
  "nomansskye.exe": "No Man's Sky",
  "oblivion.exe": "The Elder Scrolls IV: Oblivion",
  "oblivionremastered.exe": "The Elder Scrolls IV: Oblivion Remastered",
  "outlast.exe": "Outlast",
  "outlast2.exe": "Outlast 2",
  "pathfinderkingmaker.exe": "Pathfinder: Kingmaker",
  "pathfinderwrath.exe": "Pathfinder: Wrath of the Righteous",
  "pillarsofeternity.exe": "Pillars of Eternity",
  "pillarsofeternity2.exe": "Pillars of Eternity II: Deadfire",
  "planetcoaster.exe": "Planet Coaster",
  "planetcoaster2.exe": "Planet Coaster 2",
  "prey.exe": "Prey",
  "prey2.exe": "Prey (2006)",
  "quake.exe": "Quake",
  "quake2.exe": "Quake II",
  "r6.exe": "Rainbow Six Siege",
  "rainbowsix.exe": "Rainbow Six Siege",
  "rdr2_pc.exe": "Red Dead Redemption 2",
  "rdr2.exe": "Red Dead Redemption 2",
  "re2.exe": "Resident Evil 2",
  "re3.exe": "Resident Evil 3",
  "re4.exe": "Resident Evil 4",
  "re7.exe": "Resident Evil 7: Biohazard",
  "re8.exe": "Resident Evil Village",
  "remedy_alan_wake.exe": "Alan Wake Remastered",
  "remnant.exe": "Remnant: From the Ashes",
  "remnant2.exe": "Remnant II",
  "residentevil2.exe": "Resident Evil 2",
  "residentevil3.exe": "Resident Evil 3",
  "residentevil4.exe": "Resident Evil 4",
  "residentevil7.exe": "Resident Evil 7: Biohazard",
  "residentevil8.exe": "Resident Evil Village",
  "returnal.exe": "Returnal",
  "risen.exe": "Risen",
  "riseofthetombraider.exe": "Rise of the Tomb Raider",
  "satisfactory.exe": "Satisfactory",
  "sekiro.exe": "Sekiro: Shadows Die Twice",
  "shadowoftheomoraider.exe": "Shadow of the Tomb Raider",
  "shadowofthetombraider.exe": "Shadow of the Tomb Raider",
  "skyrim.exe": "The Elder Scrolls V: Skyrim",
  "skyrimse.exe": "Skyrim Special Edition",
  "soma.exe": "SOMA",
  "sonsoftheforest.exe": "Sons of the Forest",
  "spaceengineers.exe": "Space Engineers",
  "spiderman.exe": "Marvel's Spider-Man Remastered",
  "spiderman2.exe": "Marvel's Spider-Man 2",
  "stalker-cop.exe": "S.T.A.L.K.E.R.: Call of Pripyat",
  "stalker-cs.exe": "S.T.A.L.K.E.R.: Clear Sky",
  "stalker-shoc.exe": "S.T.A.L.K.E.R.: Shadow of Chornobyl Enhanced",
  "stalker2-win64-shipping.exe": "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
  "stalker2.exe": "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
  "starfield.exe": "Starfield",
  "stellar blade.exe": "Stellar Blade",
  "stellarblade.exe": "Stellar Blade",
  "stranded deep.exe": "Stranded Deep",
  "strandeddeep.exe": "Stranded Deep",
  "subnautica.exe": "Subnautica",
  "subnauticabelowzero.exe": "Subnautica: Below Zero",
  "systemshock.exe": "System Shock",
  "systemshock2.exe": "System Shock 2",
  "thecyclefront.exe": "The Cycle: Frontier",
  "theevilwithin.exe": "The Evil Within",
  "theevilwithin2.exe": "The Evil Within 2",
  "theforest.exe": "The Forest",
  "thelastofus.exe": "The Last of Us Part I",
  "thelastofuspart2.exe": "The Last of Us Part II Remastered",
  "thelongdark.exe": "The Long Dark",
  "theneworder.exe": "Wolfenstein: The New Order",
  "tld.exe": "The Long Dark",
  "tombraider.exe": "Tomb Raider (2013)",
  "torment.exe": "Torment: Tides of Numenera",
  "tyranny.exe": "Tyranny",
  "vanguard.exe": "Call of Duty: Vanguard",
  "warzone.exe": "Call of Duty: Warzone",
  "weirdwest-win64-shipping.exe": "Weird West",
  "witcher.exe": "The Witcher",
  "witcher2.exe": "The Witcher 2: Assassins of Kings",
  "witcher3.exe": "The Witcher 3: Wild Hunt",
  "wo_long.exe": "Wo Long: Fallen Dynasty",
  "wolftng.exe": "Wolfenstein: The New Order",
  "wonderlands.exe": "Tiny Tina's Wonderlands",
  "wr.exe": "EA Sports WRC",
  "wrc.exe": "EA Sports WRC",
  "xr_3da.exe": "S.T.A.L.K.E.R.: Shadow of Chernobyl",
  "youngblood.exe": "Wolfenstein: Youngblood",
};

/**
 * Returns a properly formatted display name for a process.
 * Falls back to a cleaned-up version of the exe name if not in the map.
 */
export function resolveGameTitle(processName: string): string {
  const key = processName.toLowerCase();
  if (GAME_TITLE_MAP[key]) return GAME_TITLE_MAP[key];

  return processName
    .replace(/.exe$/i, "")
    .replace(/[-_.]+/g, " ")
    .replace(/w/g, (c) => c.toUpperCase())
    .trim();
}
