/**
 * Game title map — exe name to display title.
 * Exe names sourced from PCGamingWiki, Steam crash logs, PresentMon output,
 * community launchers, GOG releases, modded clients, and legacy/retail builds.
 * For any unrecognized process, the fallback strips .exe and title-cases the name.
 */
export const GAME_TITLE_MAP: Record<string, string> = {
  // ── 0–9 ────────────────────────────────────────────────────────────────────
  "7daystodie.exe": "7 Days to Die",
  "7dtd.exe": "7 Days to Die",

  // ── A ──────────────────────────────────────────────────────────────────────
  "ac-win64-shipping.exe": "Assassin's Creed Shadows",
  "ac.exe": "Assassin's Creed",
  "acbf.exe": "Assassin's Creed IV: Black Flag",
  "aciii.exe": "Assassin's Creed III",
  "aciiiremastered.exe": "Assassin's Creed III Remastered",
  "aciiremastered.exe": "Assassin's Creed II",
  "acmirage.exe": "Assassin's Creed Mirage",
  "acodyssey.exe": "Assassin's Creed Odyssey",
  "acorigins.exe": "Assassin's Creed Origins",
  "acrogue.exe": "Assassin's Creed Rogue",
  "acs.exe": "Assetto Corsa",
  "acshadows.exe": "Assassin's Creed Shadows",
  "acstellarblade.exe": "Stellar Blade", // alias guard
  "acsyndicate.exe": "Assassin's Creed Syndicate",
  "acu.exe": "Assassin's Creed Unity",
  "acvalhalla.exe": "Assassin's Creed Valhalla",
  "age3.exe": "Age of Empires III",
  "age3y.exe": "Age of Empires III: The Asian Dynasties",
  "ageofdecadence.exe": "The Age of Decadence",
  "ageofempires2.exe": "Age of Empires II: Definitive Edition",
  "ageofempires3.exe": "Age of Empires III: Definitive Edition",
  "ageofempires4.exe": "Age of Empires IV",
  "ageofmythology.exe": "Age of Mythology: Retold",
  "alan_wake_2.exe": "Alan Wake 2",
  "alanwake.exe": "Alan Wake",
  "alanwake2.exe": "Alan Wake 2",
  "alien_isolation.exe": "Alien: Isolation",
  "alienisolation.exe": "Alien: Isolation",
  "amnesia.exe": "Amnesia: The Dark Descent",
  "amnesiarebirth.exe": "Amnesia: Rebirth",
  "amnesiatdd.exe": "Amnesia: The Dark Descent",
  "amongus.exe": "Among Us",
  "anno1800.exe": "Anno 1800",
  "anno2205.exe": "Anno 2205",
  "anno2070.exe": "Anno 2070",
  "arma3.exe": "Arma 3",
  "arma3battleye.exe": "Arma 3",
  "arma3launcher.exe": "Arma 3",
  "arma4.exe": "Arma 4",
  "ark.exe": "ARK: Survival Evolved",
  "arksurvivalascended.exe": "ARK: Survival Ascended",
  "assassinscreed.exe": "Assassin's Creed",
  "assassinscreed2.exe": "Assassin's Creed II",
  "assassinscreediiiretribution.exe": "Assassin's Creed III",
  "avengers.exe": "Marvel's Avengers",

  // ── B ──────────────────────────────────────────────────────────────────────
  "baldursgate.exe": "Baldur's Gate",
  "baldursgate2.exe": "Baldur's Gate II",
  "baldursgate3.exe": "Baldur's Gate 3",
  "batmanarkhamasylum.exe": "Batman: Arkham Asylum",
  "batmanarkhamcity.exe": "Batman: Arkham City",
  "batmanarkhamknight.exe": "Batman: Arkham Knight",
  "batmanarkhamknightlauncher.exe": "Batman: Arkham Knight",
  "batmanarkhamorigins.exe": "Batman: Arkham Origins",
  "batmanarkhamoriginscoldcoldh.exe":
    "Batman: Arkham Origins — Cold, Cold Heart",
  "bf1.exe": "Battlefield 1",
  "bf1942.exe": "Battlefield 1942",
  "bf2.exe": "Battlefield 2",
  "bf2042.exe": "Battlefield 2042",
  "bf2142.exe": "Battlefield 2142",
  "bf3.exe": "Battlefield 3",
  "bf4.exe": "Battlefield 4",
  "bf6.exe": "Battlefield 6",
  "bfbc2.exe": "Battlefield: Bad Company 2",
  "bfdc.exe": "Battlefield: Dark Company",
  "bfhardline.exe": "Battlefield: Hardline",
  "bfv.exe": "Battlefield V",
  "bg3.exe": "Baldur's Gate 3",
  "bioshock.exe": "BioShock",
  "bioshock2.exe": "BioShock 2",
  "bioshock2hd.exe": "BioShock 2 Remastered",
  "bioshockhd.exe": "BioShock Remastered",
  "bioshockinfinite.exe": "BioShock Infinite",
  "bl3.exe": "Borderlands 3",
  "blackops.exe": "Call of Duty: Black Ops",
  "blackops2.exe": "Call of Duty: Black Ops II",
  "blackops3.exe": "Call of Duty: Black Ops III",
  "blackops4.exe": "Call of Duty: Black Ops 4",
  "blackops6.exe": "Call of Duty: Black Ops 6",
  "borderlands.exe": "Borderlands",
  "borderlands2.exe": "Borderlands 2",
  "borderlands3.exe": "Borderlands 3",
  "borderlandsgotye.exe": "Borderlands: Game of the Year Edition",
  "buldersgate3.exe": "Baldur's Gate 3", // common typo exe seen in logs

  // ── C ──────────────────────────────────────────────────────────────────────
  "callofcthulhu.exe": "Call of Cthulhu",
  "callofjuarez.exe": "Call of Juarez: Gunslinger",
  "chernobylite.exe": "Chernobylite",
  "chernobylitecomplete.exe": "Chernobylite",
  "cities.exe": "Cities: Skylines",
  "cities2.exe": "Cities: Skylines II",
  "citiesskylines.exe": "Cities: Skylines",
  "citiesskylines2.exe": "Cities: Skylines II",
  "civilization5.exe": "Sid Meier's Civilization V",
  "civilization6.exe": "Sid Meier's Civilization VI",
  "civilization7.exe": "Sid Meier's Civilization VII",
  "civ5.exe": "Sid Meier's Civilization V",
  "civ6.exe": "Sid Meier's Civilization VI",
  "civ7.exe": "Sid Meier's Civilization VII",
  "clustertruck.exe": "Clustertruck",
  "cod.exe": "Call of Duty",
  "cod2.exe": "Call of Duty 2",
  "cod4.exe": "Call of Duty 4: Modern Warfare",
  "codbo4.exe": "Call of Duty: Black Ops 4",
  "codmw.exe": "Call of Duty: Modern Warfare",
  "codwaw.exe": "Call of Duty: World at War",
  "concord.exe": "Concord",
  "consoleapp.exe": "Halo 2 Project Cartographer", // H2PC legacy console wrapper
  "control_dx11.exe": "Control",
  "control_dx12.exe": "Control",
  "craftopia.exe": "Craftopia",
  "crysis.exe": "Crysis [Remastered]",
  "crysisremastered.exe": "Crysis [Remastered]",
  "crysis2.exe": "Crysis 2 [Remastered]",
  "crysis2remastered.exe": "Crysis 2 [Remastered]",
  "crysis2maxeditionlauncher.exe": "Crysis 2 Maximum Edition",
  "crysis3.exe": "Crysis 3 [Remastered]",
  "crysis3remastered.exe": "Crysis 3 [Remastered]",
  "crysiswars.exe": "Crysis Wars",
  "crysiswarsanticheat.exe": "Crysis Wars",
  "crysiswarsserver.exe": "Crysis Wars (Server)",
  "cs.exe": "Counter-Strike",
  "cs16.exe": "Counter-Strike 1.6",
  "cs2.exe": "Counter-Strike 2",
  "csgo.exe": "Counter-Strike: Global Offensive",
  "csgoclient.exe": "Counter-Strike: Global Offensive",
  "cstrike.exe": "Counter-Strike",
  "cyberpunk2077.exe": "Cyberpunk 2077",

  // ── D ──────────────────────────────────────────────────────────────────────
  "darkest.exe": "Darkest Dungeon",
  "darkestdungeon.exe": "Darkest Dungeon",
  "darkestdungeon2.exe": "Darkest Dungeon 2",
  "darksiders.exe": "Darksiders",
  "darksiders2.exe": "Darksiders II",
  "darksiders3.exe": "Darksiders III",
  "darksouls.exe": "Dark Souls Remastered",
  "darksouls2.exe": "Dark Souls II",
  "darksoulsii.exe": "Dark Souls II",
  "darksouls2sotfs.exe": "Dark Souls II: Scholar of the First Sin",
  "darksouls3.exe": "Dark Souls III",
  "darksoulsiii.exe": "Dark Souls III",
  "darksoulsremastered.exe": "Dark Souls Remastered",
  "daysgone.exe": "Days Gone",
  "dayz.exe": "DayZ",
  "dayzlauncher.exe": "DayZ",
  "dayzstandalone.exe": "DayZ",
  "deadcells.exe": "Dead Cells",
  "deadisland.exe": "Dead Island",
  "deadisland2.exe": "Dead Island 2",
  "deadislandepic.exe": "Dead Island",
  "deadislandriptide.exe": "Dead Island: Riptide",
  "deadspace.exe": "Dead Space",
  "deadspace2.exe": "Dead Space 2",
  "deadspace3.exe": "Dead Space 3",
  "deadspaceremake.exe": "Dead Space (Remake)",
  "deathloop.exe": "Deathloop",
  "deathoftheoutsider.exe": "Dishonored: Death of the Outsider",
  "deathstranding.exe": "Death Stranding",
  "deathstranding2.exe": "Death Stranding 2",
  "demeo.exe": "Demeo",
  "deusex.exe": "Deus Ex",
  "deusexhumanrev.exe": "Deus Ex: Human Revolution",
  "deusexhumanrevolution.exe": "Deus Ex: Human Revolution",
  "deusexinvisiblewar.exe": "Deus Ex: Invisible War",
  "deusexmd.exe": "Deus Ex: Mankind Divided",
  "dirtrally.exe": "DiRT Rally",
  "dirtrally2.exe": "DiRT Rally 2.0",
  "dishonored.exe": "Dishonored",
  "dishonored2.exe": "Dishonored 2",
  "divinity.exe": "Divinity: Original Sin 2",
  "divinityoriginalsin.exe": "Divinity: Original Sin",
  "divinityoriginalsin2.exe": "Divinity: Original Sin 2",
  "division.exe": "Tom Clancy's The Division",
  "division2.exe": "Tom Clancy's The Division 2",
  "thedivision2.exe": "Tom Clancy's The Division 2",
  "doom.exe": "DOOM (2016)",
  "doom1.exe": "DOOM (Classic)",
  "doom2.exe": "DOOM II (Classic)",
  "doom64.exe": "DOOM 64",
  "doom_x64.exe": "DOOM (2016)",
  "doomdark.exe": "DOOM: The Dark Ages",
  "doomdarkages.exe": "DOOM: The Dark Ages",
  "doomdarkages-win64-shipping.exe": "DOOM: The Dark Ages",
  "doometernal.exe": "DOOM Eternal",
  "doometernall.exe": "DOOM Eternal",
  "doomx64vk.exe": "DOOM Eternal",
  "dota2.exe": "Dota 2",
  "dragonage.exe": "Dragon Age: Origins",
  "dragonage2.exe": "Dragon Age II",
  "dragonageinquisition.exe": "Dragon Age: Inquisition",
  "dragonageveilguard.exe": "Dragon Age: The Veilguard",
  "dragonsdogma.exe": "Dragon's Dogma: Dark Arisen",
  "dragonsdogma2.exe": "Dragon's Dogma 2",
  "dragonsdogmadarkaris.exe": "Dragon's Dogma: Dark Arisen",
  "dysonsphereprog.exe": "Dyson Sphere Program",
  "dysonsphereprogram.exe": "Dyson Sphere Program",

  // ── E ──────────────────────────────────────────────────────────────────────
  "eft.exe": "Escape from Tarkov",
  "eldenring.exe": "Elden Ring",
  "eldenringnightreign.exe": "Elden Ring: Nightreign",
  "elex.exe": "ELEX",
  "elex2.exe": "ELEX II",
  "empyrion.exe": "Empyrion: Galactic Survival",
  "enshrouded.exe": "Enshrouded",
  "escapefromtarkov.exe": "Escape from Tarkov",
  "eu4.exe": "Europa Universalis IV",
  "exanima.exe": "Exanima",

  // ── F ──────────────────────────────────────────────────────────────────────
  "f12021.exe": "F1 2021",
  "f12022.exe": "F1 2022",
  "f12023.exe": "F1 2023",
  "f12024.exe": "F1 2024",
  "f12025.exe": "F1 2025",
  "factorio.exe": "Factorio",
  "fallout.exe": "Fallout",
  "fallout2.exe": "Fallout 2",
  "fallout3.exe": "Fallout 3",
  "fallout4.exe": "Fallout 4",
  "fallout4vr.exe": "Fallout 4 VR",
  "fallout76.exe": "Fallout 76",
  "falloutnv.exe": "Fallout: New Vegas",
  "falloutnvse.exe": "Fallout: New Vegas (NVSE)",
  "farcry.exe": "Far Cry",
  "farcry2.exe": "Far Cry 2",
  "farcry3.exe": "Far Cry 3",
  "farcry3blooddragon.exe": "Far Cry 3: Blood Dragon",
  "farcry4.exe": "Far Cry 4",
  "farcry5.exe": "Far Cry 5",
  "farcry6.exe": "Far Cry 6",
  "farcryneward.exe": "Far Cry New Dawn",
  "farcrynewdawn.exe": "Far Cry New Dawn",
  "farcryprimal.exe": "Far Cry Primal",
  "fatshark.exe": "Warhammer: Vermintide 2", // Fatshark launcher seen in logs
  "fatshark2.exe": "Warhammer: Vermintide 2",
  "ff16.exe": "Final Fantasy XVI",
  "ff7.exe": "Final Fantasy VII Remake",
  "ff7rebirth.exe": "Final Fantasy VII Rebirth",
  "ff7remake_launcher.exe": "Final Fantasy VII Remake",
  "ffxiv.exe": "Final Fantasy XIV",
  "ffxiv_dx11.exe": "Final Fantasy XIV",
  "ffxivlauncher.exe": "Final Fantasy XIV",
  "ffxv.exe": "Final Fantasy XV",
  "finalfantasyxv.exe": "Final Fantasy XV",
  "firewatch.exe": "Firewatch",
  "firstclasstroubles.exe": "First Class Trouble",
  "flightsimulator.exe": "Microsoft Flight Simulator",
  "flightsimulator2024.exe": "Microsoft Flight Simulator 2024",
  "forgottenannals.exe": "Forgotten Annals",
  "forzamotorsport.exe": "Forza Motorsport",
  "forzamotorsport7.exe": "Forza Motorsport 7",
  "frostpunk.exe": "Frostpunk",
  "frostpunk2.exe": "Frostpunk 2",
  "fw-win64-shipping.exe": "Forspoken",
  "forspoken.exe": "Forspoken",

  // ── G ──────────────────────────────────────────────────────────────────────
  "garry.exe": "Garry's Mod",
  "garrysmod.exe": "Garry's Mod",
  "ghostoftsushima.exe": "Ghost of Tsushima",
  "ghostreconbreakpoint.exe": "Ghost Recon Breakpoint",
  "ghostreconwildlands.exe": "Ghost Recon Wildlands",
  "ghostrunner.exe": "Ghostrunner",
  "ghostrunner2.exe": "Ghostrunner 2",
  "gloomwood.exe": "Gloomwood",
  "godofwar.exe": "God of War",
  "godofwarragnarok-win64-shipping.exe": "God of War: Ragnarök",
  "gothic.exe": "Gothic",
  "gothic2.exe": "Gothic 2",
  "gothic3.exe": "Gothic 3",
  "gothicremake.exe": "Gothic Remake",
  "gta5.exe": "Grand Theft Auto V",
  "gta6.exe": "Grand Theft Auto VI",
  "gtaiv.exe": "Grand Theft Auto IV",
  "gtaiv_bex.exe": "Grand Theft Auto IV",
  "gtasa.exe": "Grand Theft Auto: San Andreas",
  "gtasade.exe": "Grand Theft Auto: San Andreas Definitive Edition",
  "gtavc.exe": "Grand Theft Auto: Vice City",
  "green.exe": "Green Hell",
  "greenh.exe": "Green Hell",
  "greenhell.exe": "Green Hell",
  "groundbranch.exe": "Ground Branch",

  // ── H ──────────────────────────────────────────────────────────────────────
  "h2v.exe": "Halo 2 Vista",
  "halo.exe": "Halo: Combat Evolved",
  "halo1.exe": "Halo: Combat Evolved",
  "halo2.exe": "Halo 2 Project Cartographer",
  "halo2campaign.exe": "Halo 2 Project Cartographer (Campaign)",
  "halo2cartographer.exe": "Halo 2 Project Cartographer",
  "halo2launch.exe": "Halo 2 Project Cartographer",
  "halo2mp.exe": "Halo 2 Project Cartographer (Multiplayer)",
  "halo2vista.exe": "Halo 2 Vista",
  "haloinfiniite.exe": "Halo Infinite",
  "haloinfinite.exe": "Halo Infinite",
  "halomcc-win64-shipping.exe": "Halo: The Master Chief Collection",
  "mccwinstore-win64-shipping.exe": "Halo: The Master Chief Collection",
  "halomcc.exe": "Halo: The Master Chief Collection",
  "hce.exe": "Halo: Combat Evolved",
  "haloce.exe": "Halo: Combat Evolved",
  "haloceonline.exe": "Halo: Online (ElDewrito)",
  "eldorito.exe": "Halo: Online (ElDewrito)",
  "eldewrito.exe": "Halo: Online (ElDewrito)",
  "helldivers2.exe": "Helldivers 2",
  "heroesofmightandmagic3.exe": "Heroes of Might and Magic III",
  "heroes3.exe": "Heroes of Might and Magic III",
  "heroesofmightandmagic5.exe": "Heroes of Might and Magic V",
  "hfw-win64-shipping.exe": "Horizon Forbidden West",
  "hoi4.exe": "Hearts of Iron IV",
  "horizon4.exe": "Forza Horizon 4",
  "horizon5.exe": "Forza Horizon 5",
  "horizonforbiddenwest-win64-shipping.exe": "Horizon Forbidden West",
  "horizonforbiddenwest.exe": "Horizon Forbidden West",
  "horizonzerodawn.exe": "Horizon Zero Dawn Remastered",
  "horizonzerodawnremastered.exe": "Horizon Zero Dawn Remastered",
  "hotlinemiami.exe": "Hotline Miami",
  "hotlinemiami2.exe": "Hotline Miami 2: Wrong Number",

  // ── I ──────────────────────────────────────────────────────────────────────
  "icarus-win64-shipping.exe": "Icarus",
  "icarus.exe": "Icarus",
  "infinity.exe": "Halo 4 (MCC)", // internal name seen in some MCC builds
  "insomnia.exe": "InSomnia: The Ark",

  // ── J ──────────────────────────────────────────────────────────────────────
  "jagexlauncher.exe": "Jagex Launcher",
  "jurassicworldevolution.exe": "Jurassic World Evolution",
  "jurassicworldevolution2.exe": "Jurassic World Evolution 2",
  "justcause3.exe": "Just Cause 3",
  "justcause4.exe": "Just Cause 4",

  // ── K ──────────────────────────────────────────────────────────────────────
  "kcd2.exe": "Kingdom Come: Deliverance II",
  "kingdomcome.exe": "Kingdom Come: Deliverance",
  "kingdomcome2.exe": "Kingdom Come: Deliverance II",
  "kingdomcomedeliverancerp.exe": "Kingdom Come: Deliverance",

  // ── L ──────────────────────────────────────────────────────────────────────
  "l4d.exe": "Left 4 Dead",
  "l4d2.exe": "Left 4 Dead 2",
  "lastofuspart1.exe": "The Last of Us Part I",
  "lastofuspart2.exe": "The Last of Us Part II Remastered",
  "left4dead.exe": "Left 4 Dead",
  "left4dead2.exe": "Left 4 Dead 2",
  "liesofp.exe": "Lies of P",
  "lineofdefense.exe": "Line of Defense Tactics",
  "littlenightmares.exe": "Little Nightmares",
  "littlenightmares2.exe": "Little Nightmares II",
  "lotf.exe": "Lords of the Fallen",
  "lordsofthefallen.exe": "Lords of the Fallen",

  // ── M ──────────────────────────────────────────────────────────────────────
  "mafia-win64-shipping.exe": "Mafia: The Old Country",
  "mafia.exe": "Mafia: Definitive Edition",
  "mafia2de.exe": "Mafia II: Definitive Edition",
  "mafia3.exe": "Mafia III",
  "mafia4.exe": "Mafia: The Old Country",
  "mafiaoldcountry.exe": "Mafia: The Old Country",
  "mafiaremastered.exe": "Mafia: Definitive Edition",
  "mankind_divided.exe": "Deus Ex: Mankind Divided",
  "masseffect1.exe": "Mass Effect 1 [Legendary Edition]",
  "masseffect2.exe": "Mass Effect 2 [Legendary Edition]",
  "masseffect3.exe": "Mass Effect 3 [Legendary Edition]",
  "masseffectandromeda.exe": "Mass Effect: Andromeda",
  "masseffectlauncher.exe": "Mass Effect Legendary Edition",
  "masseffectlegendaryedition.exe": "Mass Effect Legendary Edition",
  "me1game-win64-shipping.exe": "Mass Effect 1 [Legendary Edition]",
  "me2game-win64-shipping.exe": "Mass Effect 2 [Legendary Edition]",
  "me3game-win64-shipping.exe": "Mass Effect 3 [Legendary Edition]",
  "me3biotic.exe": "Mass Effect 3 [Legendary Edition]",
  "metro2033.exe": "Metro 2033",
  "metro2033redux.exe": "Metro 2033 Redux",
  "metroexodus.exe": "Metro Exodus",
  "metroexodusenhanced.exe": "Metro Exodus Enhanced Edition",
  "metrolastlight.exe": "Metro: Last Light",
  "metrolastlightredux.exe": "Metro: Last Light Redux",
  "mhrise.exe": "Monster Hunter Rise",
  "mhrise_sunbreak.exe": "Monster Hunter Rise: Sunbreak",
  "mhwilds.exe": "Monster Hunter Wilds",
  "mhworld.exe": "Monster Hunter: World",
  "microsoftflightsimulator.exe": "Microsoft Flight Simulator",
  "milemorales.exe": "Marvel's Spider-Man: Miles Morales",
  "minecraftlauncher.exe": "Minecraft",
  "minecraft.exe": "Minecraft",
  "modernwarfare.exe": "Call of Duty: Modern Warfare",
  "modernwarfare2.exe": "Call of Duty: Modern Warfare II",
  "modernwarfare3.exe": "Call of Duty: Modern Warfare III",
  "monsterh-win64-shipping.exe": "Monster Hunter: World",
  "monsterhunterworld.exe": "Monster Hunter: World",
  "monsterhunterworldice.exe": "Monster Hunter: World — Iceborne",
  "morrowind.exe": "The Elder Scrolls III: Morrowind",
  "morrowindopenmw.exe": "OpenMW (Morrowind)",
  "msfs.exe": "Microsoft Flight Simulator",
  "msfs2024.exe": "Microsoft Flight Simulator 2024",
  "mxgp.exe": "MXGP",
  "mxgp2.exe": "MXGP2",
  "mxgp3.exe": "MXGP3",

  // ── N ──────────────────────────────────────────────────────────────────────
  "needforseedunbound.exe": "Need for Speed: Unbound",
  "needforspeedheat.exe": "Need for Speed: Heat",
  "needforspeedmostw.exe": "Need for Speed: Most Wanted (2012)",
  "needforspeedrivals.exe": "Need for Speed: Rivals",
  "newcolossus.exe": "Wolfenstein II: The New Colossus",
  "neworder.exe": "Wolfenstein: The New Order",
  "nfsheat.exe": "Need for Speed: Heat",
  "nfsmostwanted.exe": "Need for Speed: Most Wanted (2012)",
  "nfsrivals.exe": "Need for Speed: Rivals",
  "nfsunbound.exe": "Need for Speed: Unbound",
  "nioh.exe": "Nioh: Complete Edition",
  "nioh2.exe": "Nioh 2",
  "nms.exe": "No Man's Sky",
  "nomansskye.exe": "No Man's Sky",
  "nomansskysteam.exe": "No Man's Sky",

  // ── O ──────────────────────────────────────────────────────────────────────
  "oblivion.exe": "The Elder Scrolls IV: Oblivion",
  "oblivionremastered.exe": "The Elder Scrolls IV: Oblivion Remastered",
  "obse_loader.exe": "The Elder Scrolls IV: Oblivion (OBSE)",
  "openmw.exe": "OpenMW (Morrowind)",
  "outlast.exe": "Outlast",
  "outlast2.exe": "Outlast 2",
  "outlasttrialsrelease.exe": "The Outlast Trials",
  "outlasttrials.exe": "The Outlast Trials",
  "outerwilds.exe": "Outer Wilds",
  "outerworlds.exe": "The Outer Worlds",
  "outerworldsspacemanedition.exe": "The Outer Worlds: Spacer's Choice Edition",
  "outriderslaunch.exe": "Outriders",
  "outriders-win64-shipping.exe": "Outriders",

  // ── P ──────────────────────────────────────────────────────────────────────
  "pathfinderkingmaker.exe": "Pathfinder: Kingmaker",
  "pathfinderwrath.exe": "Pathfinder: Wrath of the Righteous",
  "pf2e.exe": "Pathfinder: Wrath of the Righteous",
  "pillarsofeternity.exe": "Pillars of Eternity",
  "pillarsofeternity2.exe": "Pillars of Eternity II: Deadfire",
  "planetcoaster.exe": "Planet Coaster",
  "planetcoaster2.exe": "Planet Coaster 2",
  "planetcrafter.exe": "The Planet Crafter",
  "planetcrafter-win64-shipping.exe": "The Planet Crafter",
  "plunkbat.exe": "PUBG: Battlegrounds", // legacy debug name
  "prey.exe": "Prey",
  "prey2.exe": "Prey (2006)",
  "pubg.exe": "PUBG: Battlegrounds",
  "pubglite.exe": "PUBG Lite",

  // ── Q ──────────────────────────────────────────────────────────────────────
  "quake.exe": "Quake",
  "quake2.exe": "Quake II",
  "quake3.exe": "Quake III Arena",
  "quake4.exe": "Quake 4",
  "quakechampions.exe": "Quake Champions",
  "quakelive.exe": "Quake Live",

  // ── R ──────────────────────────────────────────────────────────────────────
  "r6.exe": "Rainbow Six Siege",
  "rainbowsix.exe": "Rainbow Six Siege",
  "rainbowsixextraction.exe": "Rainbow Six Extraction",
  "rdr2_pc.exe": "Red Dead Redemption 2",
  "rdr2.exe": "Red Dead Redemption 2",
  "re2.exe": "Resident Evil 2",
  "re3.exe": "Resident Evil 3",
  "re4.exe": "Resident Evil 4",
  "re7.exe": "Resident Evil 7: Biohazard",
  "re8.exe": "Resident Evil Village",
  "remedy_alan_wake.exe": "Alan Wake Remastered",
  "remnant.exe": "Remnant: From the Ashes",
  "remnant2.exe": "Remnant II",
  "residentevil0.exe": "Resident Evil 0",
  "residentevil1.exe": "Resident Evil (HD)",
  "residentevil2.exe": "Resident Evil 2",
  "residentevil3.exe": "Resident Evil 3",
  "residentevil4.exe": "Resident Evil 4",
  "residentevil7.exe": "Resident Evil 7: Biohazard",
  "residentevil8.exe": "Resident Evil Village",
  "residentevilreverse.exe": "Resident Evil Re:Verse",
  "returnal.exe": "Returnal",
  "risen.exe": "Risen",
  "risen2.exe": "Risen 2: Dark Waters",
  "risen3.exe": "Risen 3: Titan Lords",
  "riseofthetombraider.exe": "Rise of the Tomb Raider",
  "robocop-win64-shipping.exe": "RoboCop: Rogue City",
  "robocoproguecity.exe": "RoboCop: Rogue City",
  "rocketsoccer.exe": "Rocket League",
  "rocketleague.exe": "Rocket League",
  "rogue-city-win64-shipping.exe": "RoboCop: Rogue City",
  "rslaunch.exe": "Rainbow Six Siege",
  "runelite.exe": "RuneLite",

  // ── S ──────────────────────────────────────────────────────────────────────
  "satisfactory.exe": "Satisfactory",
  "satisfactory-win64-shipping.exe": "Satisfactory",
  "sekiro.exe": "Sekiro: Shadows Die Twice",
  "shadowoftheomoraider.exe": "Shadow of the Tomb Raider",
  "shadowofthetombraider.exe": "Shadow of the Tomb Raider",
  "sherlock.exe": "Sherlock Holmes: Chapter One",
  "sherlock2.exe": "Sherlock Holmes: The Awakened",
  "shipbreaker.exe": "Hardspace: Shipbreaker",
  "hardspaceshipbreaker.exe": "Hardspace: Shipbreaker",
  "shogun2.exe": "Total War: Shogun 2",
  "sifu.exe": "Sifu",
  "sifu-win64-shipping.exe": "Sifu",
  "skyrim.exe": "The Elder Scrolls V: Skyrim",
  "skyrimse.exe": "Skyrim Special Edition",
  "skyrimvr.exe": "Skyrim VR",
  "skse64_loader.exe": "Skyrim Special Edition (SKSE64)",
  "skse_loader.exe": "The Elder Scrolls V: Skyrim (SKSE)",
  "soma.exe": "SOMA",
  "sonsoftheforest.exe": "Sons of the Forest",
  "spacemarines2-win64-shipping.exe": "Warhammer 40,000: Space Marine 2",
  "spacemarines2.exe": "Warhammer 40,000: Space Marine 2",
  "spaceengineers.exe": "Space Engineers",
  "spiderman.exe": "Marvel's Spider-Man Remastered",
  "spiderman2.exe": "Marvel's Spider-Man 2",
  "stalker-cop.exe": "S.T.A.L.K.E.R.: Call of Pripyat",
  "stalker-cs.exe": "S.T.A.L.K.E.R.: Clear Sky",
  "stalker-shoc.exe": "S.T.A.L.K.E.R.: Shadow of Chornobyl Enhanced",
  "stalker2-win64-shipping.exe": "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
  "stalker2.exe": "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
  "stalkeranomaly.exe": "S.T.A.L.K.E.R. Anomaly",
  "xrengine.exe": "S.T.A.L.K.E.R. Legends of the Zone Trilogy",
  "starfield.exe": "Starfield",
  "starfieldlauncher.exe": "Starfield",
  "stars.exe": "Stellaris",
  "starsector.exe": "Starsector",
  "stellaris.exe": "Stellaris",
  "stellar blade.exe": "Stellar Blade",
  "stellarblade.exe": "Stellar Blade",
  "stellarblade-win64-shipping.exe": "Stellar Blade",
  "stranded deep.exe": "Stranded Deep",
  "strandeddeep.exe": "Stranded Deep",
  "subnautica.exe": "Subnautica",
  "subnauticabelowzero.exe": "Subnautica: Below Zero",
  "systemshock.exe": "System Shock",
  "systemshock2.exe": "System Shock 2",
  "systemshockremake.exe": "System Shock (Remake)",

  // ── T ──────────────────────────────────────────────────────────────────────
  "tekken7.exe": "Tekken 7",
  "tekken8.exe": "Tekken 8",
  "terraria.exe": "Terraria",
  "thecyclefront.exe": "The Cycle: Frontier",
  "theevilwithin.exe": "The Evil Within",
  "theevilwithin2.exe": "The Evil Within 2",
  "theforest.exe": "The Forest",
  "thelastofus.exe": "The Last of Us Part I",
  "thelastofuspart2.exe": "The Last of Us Part II Remastered",
  "thelongdark.exe": "The Long Dark",
  "thesurge.exe": "The Surge",
  "thesurge2.exe": "The Surge 2",
  "thewalkingdead.exe": "The Walking Dead",
  "thewalkingdeads2.exe": "The Walking Dead: Season Two",
  "thewalkingdeadseason3.exe": "The Walking Dead: A New Frontier",
  "thewalkingdeadseason4.exe": "The Walking Dead: The Final Season",
  "ticwatch.exe": "Returnal", // rare crash log alias
  "tld.exe": "The Long Dark",
  "tlou1.exe": "The Last of Us Part I",
  "tlou2.exe": "The Last of Us Part II Remastered",
  "tloupart1.exe": "The Last of Us Part I",
  "tloupart2.exe": "The Last of Us Part II Remastered",
  "tombraider.exe": "Tomb Raider (2013)",
  "tombraider2013.exe": "Tomb Raider (2013)",
  "torment.exe": "Torment: Tides of Numenera",
  "totalwar3k.exe": "Total War: Three Kingdoms",
  "totalwarattila.exe": "Total War: Attila",
  "totalwarthreekingdoms.exe": "Total War: Three Kingdoms",
  "totalwarthrone.exe": "A Total War Saga: Thrones of Britannia",
  "totalwarwarhammer.exe": "Total War: Warhammer",
  "totalwarwarhammer2.exe": "Total War: Warhammer II",
  "totalwarwarhammer3.exe": "Total War: Warhammer III",
  "tyranny.exe": "Tyranny",

  // ── U ──────────────────────────────────────────────────────────────────────
  "underrail.exe": "Underrail",
  "unrealchampions.exe": "Unreal Championship",
  "unrealtournament.exe": "Unreal Tournament",
  "unrealtournament2004.exe": "Unreal Tournament 2004",
  "unrealtournament3.exe": "Unreal Tournament 3",

  // ── V ──────────────────────────────────────────────────────────────────────
  "vanguard.exe": "Call of Duty: Vanguard",
  "valorant-win64-shipping.exe": "VALORANT",
  "valorant.exe": "VALORANT",
  "vampyr.exe": "Vampyr",
  "vermintide2.exe": "Warhammer: Vermintide 2",

  // ── W ──────────────────────────────────────────────────────────────────────
  "warframe.exe": "Warframe",
  "warhammer40kdarktide.exe": "Warhammer 40,000: Darktide",
  "darktide-win64-shipping.exe": "Warhammer 40,000: Darktide",
  "warzone.exe": "Call of Duty: Warzone",
  "warzone2.exe": "Call of Duty: Warzone 2.0",
  "weirdwest-win64-shipping.exe": "Weird West",
  "witcher.exe": "The Witcher",
  "witcher2.exe": "The Witcher 2: Assassins of Kings",
  "witcher3.exe": "The Witcher 3: Wild Hunt",
  "witcher4.exe": "The Witcher 4",
  "witcher4-win64-shipping.exe": "The Witcher 4",
  "wo_long.exe": "Wo Long: Fallen Dynasty",
  "wolftng.exe": "Wolfenstein: The New Order",
  "wolfenstein.exe": "Wolfenstein: The New Order",
  "wonderlands.exe": "Tiny Tina's Wonderlands",
  "wr.exe": "EA Sports WRC",
  "wrc.exe": "EA Sports WRC",

  // ── X ──────────────────────────────────────────────────────────────────────
  "x4.exe": "X4: Foundations",
  "xr_3da.exe": "S.T.A.L.K.E.R.: Shadow of Chernobyl",
  "xdefiant.exe": "XDefiant",
  "xdefiant-win64-shipping.exe": "XDefiant",

  // ── Y ──────────────────────────────────────────────────────────────────────
  "youngblood.exe": "Wolfenstein: Youngblood",

  // ── Z ──────────────────────────────────────────────────────────────────────
  "zombiearmytrilogy.exe": "Zombie Army Trilogy",
  "zombiearmy4.exe": "Zombie Army 4: Dead War",
};

/**
 * Returns a properly formatted display name for a process.
 * Falls back to a cleaned-up version of the exe name if not in the map.
 * Handles camelCase splitting while preserving ALL_CAPS substrings.
 */
export function resolveGameTitle(processName: string): string {
  const key = processName.toLowerCase();
  if (GAME_TITLE_MAP[key]) return GAME_TITLE_MAP[key];

  return (
    processName
      .replace(/\.exe$/i, "")
      // Split camelCase boundaries: lowercase/digit followed by uppercase,
      // but only when the uppercase starts a new word (not inside an all-caps run)
      .replace(/([a-z\d])([A-Z][a-z])/g, "$1 $2")
      // Also split when transitioning out of an all-caps run into a capitalized word
      .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2")
      .replace(/[-_.]+/g, " ")
      .replace(/\b\w/g, (c) => c.toUpperCase())
      .trim()
  );
}
